import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers";
import detectEthereumProvider from '@metamask/detect-provider';

async function initEther() {
  const ethereumProvider:any = await detectEthereumProvider();
  if (ethereumProvider) {
    // From now on, this should always be true:
    // provider === window.ethereum
    const provider = new ethers.providers.Web3Provider(ethereumProvider)
    // const provider = new ethers.providers.JsonRpcProvider();
    const signer = provider.getSigner()
    console.log(signer);
    console.log('signer address', await signer.getAddress());
    // console.log(await (await signer.getBalance()).toNumber())

    const n = await provider.getBlockNumber()
    // const balance = await provider.getBalance("ethers.eth")
    console.log('blocks', n);
    // console.log(balance);
    await ethereumProvider.request({ method: 'eth_requestAccounts' });
    // const balance = await provider.getBalance("ethers.eth")
    // console.log(balance);
    // The Contract object
    const daiAddress = "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512";
    const daiAbi = [
      // Some details about the token
      "function greet() public view returns (string memory)",
      "function setGreeting(string memory _greeting)",
      
      // "function symbol() view returns (string)",
    
      // // Get the account balance
      // "function balanceOf(address) view returns (uint)",
    
      // // Send some of your tokens to someone else
      // "function transfer(address to, uint amount)",
    
      // // An event triggered whenever anyone transfers to someone else
      // "event Transfer(address indexed from, address indexed to, uint amount)"
    ];
    const daiContract = new ethers.Contract(daiAddress, daiAbi, signer);
    console.log({daiContract});
    
    try{
      console.log(await daiContract.greet())
      // await daiContract.setGreeting('hahahhahahahah')
      // console.log(await daiContract.greet())
      // console.log(await daiContract.getBalance())

    } catch(e) {
      console.warn(e)
    }

  } else {
    console.log('Please install MetaMask!');
  }

}
initEther();
export default function Home() {
  ethers
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="bg-black">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

